# redirect HTTP to HTTPS
server {
    listen 80;
    server_name mediroutines.sanketgupta.tech;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name mediroutines.sanketgupta.tech;

    ssl_certificate /etc/letsencrypt/live/mediroutines.sanketgupta.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mediroutines.sanketgupta.tech/privkey.pem;

    # forward /api/ requests to backend
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # forward everything else to frontend
    location / {
        proxy_pass http://client:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}